# railway.toml
[build]
buildCommand = "cd src/backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd src/backend && uvicorn app:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.environment]
PYTHON_VERSION = "3.11"

[deploy.environment]
PYTHONPATH = "/workspace/src/backend"